### ISSUE TITLE
[feature request] Interface to get executed job result

### ISSUE THREAD

**Issue by chezou** [treasure-data/pandas-td#2]
I need an api for getting executed job result easy to use like following.

```python
df = td.read_td_job(engine, job_id)
```

I know I can get using `ResultProxy` but it is dull...

```python
df = td.td.ResultProxy(engine, con.client.job(job_id)).to_dataframe()
```

**Comment by hogelog** [comment]
+1

**Comment by k24d** [comment]
Actually this is a feature I have also wanted to add.  I'll add it soon.

**Comment by k24d** [comment]
Implemented by b1a138c.  You can use it as follows:

```python
df = td.read_td_job(35809747, engine)
````

I'll release a new version later today.

**Comment by k24d** [comment]
Released v0.8.5.

**Comment by hogelog** [comment]
:tada:

**Comment by chezou** [comment]
🎊
2015年10月9日(金) 20:50 hogelog <notifications@github.com>:

**Comment by SamuraiT** [comment]
:dancers: :tada:
