### ISSUE TITLE
to_td doesn't seem to import columns where a majority of rows are NaN

### ISSUE THREAD

**Issue by Noxeangel** [treasure-data/pandas-td#6]
I have a dataframe to import but a vast majority of some rows in 2 of the columns are blanks (the other columns don't have any blanks).
When I use 'dtypes' on the DataFrame i get a float64 for those columns.
After a successful import usin "to_td" when I look at may table in TD those 2 columns are missing.
Is it because the first record uploaded for those columns is blank?
Is there a way to sort my DataFrame to avoid that or a parameter in the "to_td" method?

**Comment by k24d** [comment]
Hmm, ``to_td()`` splits a dataframe into small chunks (with 10,000 rows by default) when uploading.  There might be a case TD cannot detect those columns on the initial upload.  Currently there is no way to define schema explicitly from ``to_td()``, unfortunately.  It might be a good idea to have an option that forces setting schema.

In the meantime, could you try updating table schema manually, either from the Console or by ``td schema`` command?

**Comment by Noxeangel** [comment]
My dataframe is below the chunk size and I managed to force the detection of those columns by sorting the values of the DF and put the na values first (looks like "to_td" starts with the last rows).
If I need to import larger datasets I'll use the toolbelt. Thanks!

**Comment by k24d** [comment]
Interesting.  I'll investigate details when I have a chance.
